define_items:
  - key: product_version_define
    value: "2"
command:
  - type: Copy
    source: src/abc/*
    destination: target/
    gitignore_path: .gitignore
    use_gitignore: true
  - type: Replace
    source: "test_src.txt"
    regex: "Hello"
    replacement: "Hello, {product_version_define}"
  - type: Copy
    source: "src/efg/*"
    destination: "target/efg"
    gitignore_path: ".gitignore"
    use_gitignore: true
  - type: Run
    command: "echo 'Build complete!'"